### ISSUE TITLE
What is the future plan of this torchchat project?

### ISSUE THREAD

**Issue by yanbing-j** [pytorch/torchchat#1114]
### 🐛 Describe the bug

Torchchat provides a solution of running LLM with PyTorch optimization on servers, desktop and mobile.

May I know what is the future plan of this project? Is there any new features to finish to encourage users to use Torchchat as a solution?

**Comment by yanbing-j** [comment]
cc @Guobing-Chen @jgong5 @mingfeima

**Comment by byjlw** [comment]
### The Purpose of this Project

**Fill the LLM inference gap in PyTorch's E2E ecosystem** and provide seamless integration with other projects like torchtune, AO and core​

​**Showcase the best way to run local LLMs** using the latest PyTorch features for your model and target device​

**Reduce the effort** required to run LLMs using PyTorch​

### The Direction of this Project

_Strengthening Integration with other PyTorch projects like AO, and Tune​_

_​Cranking on Performance including GPU, CPU, and Edge​_

_​Expanding Model Support including upcoming Llama and diffusion models ​_

_Enabling Distributed Compute (Multi-GPU and Multi-Node)​_

### To Contribute

Scan through the open issues and take an unclaimed item
We try to provide enough clarity in these issues for anyone to contribute
If you want to add something new, please file an issue first so that we can discuss the details. This will save time ensure your PR gets accepted. 

**Please Review the [Contributing Guidelines ](https://github.com/pytorch/torchchat/blob/main/CONTRIBUTING.md)for more details**
